=== OMAR701/school-manage/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:complexType name="Email">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="Type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="personnel"/>
                            <xs:enumeration value="academique"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="Tele">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="Type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="fixe"/>
                            <xs:enumeration value="portable"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="enseignants">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="enseingnant">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="CIN" type="xs:string"/>
                        <xs:element name="NOM" type="xs:string"/>
                        <xs:element name="PRENOM" type="xs:string"/>
                        <xs:element maxOccurs="unbounded" name="Tele" type="Tele"/>
                        <xs:element maxOccurs="unbounded" name="Email" type="Email"/>
                        <xs:element name="specialite" type="xs:string"/>
                        <xs:element name="Depatement">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="GI"/>
                                    <xs:enumeration value="TM"/>
                                    <xs:enumeration value="TIMQ"/>
                                    <xs:enumeration value="GIM"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="IDens" type="xs:ID"/>
                </xs:complexType>
                <!--  jkbkjn!-->
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="etudiants">
        <xs:sequence>
            <xs:element name="etudiant" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="CIN" type="xs:string"/>
                        <xs:element name="NOM" type="xs:string"/>
                        <xs:element name="PRENOM" type="xs:string"/>
                        <xs:element maxOccurs="unbounded" name="Tele" type="Tele"/>
                        <xs:element maxOccurs="unbounded" name="Email" type="Email"/>
                        <xs:element name="DateDenaissance" type="xs:date"/>
                        <xs:element name="adresse" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="rue" type="xs:string"/>
                                    <xs:element name="Ville" type="xs:string"/>
                                    <xs:element name="numero" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="IDEtu" type="xs:ID"/>
                    <xs:attribute name="filiere" type="xs:IDREF"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="modules">
        <xs:sequence>
            <xs:element name="module" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Nom" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="Coordonnateur" type="xs:IDREF"/>
                    <xs:attribute name="IDmod" type="xs:ID"/>
                    <xs:attribute name="filiere" type="xs:IDREF"/>
                    <xs:attribute name="semestre">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="S5"/>
                                <xs:enumeration value="S6"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="matieres">
        <xs:sequence>
            <xs:element name="matiere" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Intitule" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="module" type="xs:IDREF"/>
                    <xs:attribute name="enseingnat" type="xs:IDREF"/>
                    <xs:attribute name="IDMatiere" type="xs:ID"/>
                    <xs:attribute name="coefficient" type="xs:double"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="notes">
        <xs:sequence>
            <xs:element name="note" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="IDEtudiant" type="xs:IDREF"/>
                    <xs:attribute name="valeur">
                        <xs:simpleType>
                            <xs:restriction base="xs:decimal">
                                <xs:minInclusive value="0"/>
                                <xs:maxInclusive value="20"/>
                                <xs:totalDigits value="4"/>
                                <xs:fractionDigits value="2"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="exam" type="xs:IDREF"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="filieres">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="filiere">
                <xs:complexType>
                    <xs:attribute name="IDfil" type="xs:ID"/>
                    <xs:attribute name="NomFil" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Exams">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="exam">
                <xs:complexType>
                    <xs:attribute name="IDexam" type="xs:ID"/>
                    <xs:attribute name="type">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Ds"/>
                                <xs:enumeration value="Exam"/>
                                <xs:enumeration value="Projet"/>
                                <xs:enumeration value="Mat"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="Matexam" type="xs:IDREF"/>
                    <xs:attribute name="coefficient" type="xs:double"> </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="EST">
        <xs:sequence>
            <xs:element name="enseignants" type="enseignants" maxOccurs="unbounded"/>
            <xs:element minOccurs="1" name="etudiants" type="etudiants" maxOccurs="unbounded"/>
            <xs:element name="matieres" type="matieres" maxOccurs="unbounded"/>
            <xs:element name="Notes" type="notes" maxOccurs="unbounded"/>
            <xs:element name="modules" type="modules" maxOccurs="unbounded"/>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="Filieres" type="filieres"/>
            <xs:element minOccurs="1" name="Examens" type="Exams"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="EST">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="EST"> </xs:extension>
            </xs:complexContent>
        </xs:complexType>
        <xs:key name="IDens">
            <xs:selector xpath="enseignants/enseingnant"/>
            <xs:field xpath="@IDens"/>
        </xs:key>
        <xs:keyref refer="IDens" name="fk_ems_mod">
            <xs:selector xpath="modules/module"/>
            <xs:field xpath="@Coordonnateur"/>
        </xs:keyref>
        <xs:key name="IDmod">
            <xs:selector xpath="modules/module"/>
            <xs:field xpath="@IDmod"/>
        </xs:key>
        <xs:keyref refer="IDmod" name="fk_mat_mod">
            <xs:selector xpath="matieres/matiere"/>
            <xs:field xpath="@module"/>
        </xs:keyref>

        <xs:keyref refer="IDens" name="fk_mat_ens">
            <xs:selector xpath="matieres/matiere"/>
            <xs:field xpath="@enseingnat"/>
        </xs:keyref>


        <xs:key name="IDetu">
            <xs:selector xpath="etudiants/etudiant"/>
            <xs:field xpath="@IDEtu"/>
        </xs:key>
        <xs:keyref refer="IDetu" name="fk_etu_note">
            <xs:selector xpath="Notes/note"/>
            <xs:field xpath="@IDEtudiant"/>
        </xs:keyref>
        <xs:key name="IDexam">
            <xs:selector xpath="Examens/exam"/>
            <xs:field xpath="@IDexam"/>
        </xs:key>
        <xs:keyref refer="IDexam" name="fk_exam_note">
            <xs:selector xpath="Notes/note"/>
            <xs:field xpath="@exam"/>
        </xs:keyref>
        <xs:key name="IDmat">
            <xs:selector xpath="matieres/matiere"/>
            <xs:field xpath="@IDMatiere"/>
        </xs:key>
        <xs:keyref refer="IDmat" name="fk_mat_exam">
            <xs:selector xpath="Examens/exam"/>
            <xs:field xpath="@Matexam"/>
        </xs:keyref>

        <xs:key name="IDfil">
            <xs:selector xpath="Filieres/filiere"/>
            <xs:field xpath="@IDfil"/>
        </xs:key>
        <xs:keyref refer="IDfil" name="fk_Fil_mod">
            <xs:selector xpath="modules/module"/>
            <xs:field xpath="@filiere"/>
        </xs:keyref>


    </xs:element>
</xs:schema>

=== OMAR701/school-manage/xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="TP4.xsl"?>
<EST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <enseignants>
        <enseingnant IDens="E02">
            <CIN>JE398127</CIN>
            <NOM>BAKKAS</NOM>
            <PRENOM>Jamal</PRENOM>
            <Tele Type="portable">0645630921</Tele>
            <Email Type="academique">Bakkas.jamal@uca.ma</Email>
            <specialite>info</specialite>
            <Depatement>GI</Depatement>
        </enseingnant>
        <enseingnant IDens="E01">
            <CIN>JM4324</CIN>
            <NOM>Chekri</NOM>
            <PRENOM>Abderahman</PRENOM>
            <Tele Type="fixe">0793512740</Tele>
            <Email Type="personnel">chekri@gmail.com</Email>
            <specialite>info</specialite>
            <Depatement>GI</Depatement>
        </enseingnant>
        <enseingnant IDens="E03">
            <CIN>HA246382</CIN>
            <NOM>ELkouri</NOM>
            <PRENOM>Rachid</PRENOM>
            <Tele Type="fixe">0693623812</Tele>
            <Email Type="personnel">ELKOURI@gmail.com</Email>
            <specialite>info</specialite>
            <Depatement>GI</Depatement>
        </enseingnant>    
        <enseingnant IDens="E04">
            <CIN>ZE378291</CIN>
            <NOM>BAYAR</NOM>
            <PRENOM>Abdelouahed</PRENOM>
            <Tele Type="fixe">0608913245</Tele>
            <Email Type="personnel">bayar.abdo@gmail.com</Email>
            <specialite>info</specialite>
            <Depatement>GI</Depatement>
        </enseingnant>
        <enseingnant IDens="E05">
            <CIN>HG237652</CIN>
            <NOM>ESALIH</NOM>
            <PRENOM>Mohammed</PRENOM>
            <Tele Type="fixe">0693524309</Tele>
            <Email Type="personnel">Salih.mohamed@gmail.com</Email>
            <specialite>info</specialite>
            <Depatement>GI</Depatement>
        </enseingnant>
        <enseingnant IDens="E06">
            <CIN>AR764235</CIN>
            <NOM>ABDELAOUI</NOM>
            <PRENOM>Said</PRENOM>
            <Tele Type="fixe">0698635428</Tele>
            <Email Type="personnel">Abdelaoui.said@gmail.com</Email>
            <specialite>info</specialite>
            <Depatement>GI</Depatement>
        </enseingnant>
        <enseingnant IDens="E07">
            <CIN>LM872420</CIN>
            <NOM>ALAOUI</NOM>
            <PRENOM>Othman</PRENOM>
            <Tele Type="fixe">0686754324</Tele>
            <Email Type="personnel">Alaoui.othman@gmail.com</Email>
            <specialite>info</specialite>
            <Depatement>GI</Depatement>
        </enseingnant>
        <enseingnant IDens="E08">
            <CIN>ZT510983</CIN>
            <NOM>MOUNIR</NOM>
            <PRENOM>Ilham</PRENOM>
            <Tele Type="fixe">0635471821</Tele>
            <Email Type="personnel">Ilham.mounir@gmail.com</Email>
            <specialite>info</specialite>
            <Depatement>GI</Depatement>
        </enseingnant>
        <enseingnant IDens="E09">
            <CIN>RE082981</CIN>
            <NOM>ARHID</NOM>
            <PRENOM>Khadija</PRENOM>
            <Tele Type="fixe">0613241174</Tele>
            <Email Type="personnel">Arhid.m@gmail.com</Email>
            <specialite>info</specialite>
            <Depatement>GI</Depatement>
        </enseingnant>
        <enseingnant IDens="E10">
            <CIN>RE082981</CIN>
            <NOM>MAAROUF</NOM>
            <PRENOM>HAMID</PRENOM>
            <Tele Type="fixe">0642331539</Tele>
            <Email Type="personnel">MAAROUF.hamid@gmail.com</Email>
            <specialite>info</specialite>
            <Depatement>GI</Depatement>
        </enseingnant>
        <enseingnant IDens="E11">
            <CIN>RE082981</CIN>
            <NOM>BENHADOUCHE</NOM>
            <PRENOM>Mohammed</PRENOM>
            <Tele Type="fixe">0642331539</Tele>
            <Email Type="personnel">MAAROUF.hamid@gmail.com</Email>
            <specialite>info</specialite>
            <Depatement>GI</Depatement>
        </enseingnant>
    </enseignants>
    <etudiants>
        <etudiant IDEtu="ET01"  filiere="F01">
            <CIN>JE283017</CIN>
            <NOM>AIT AYAD</NOM>
            <PRENOM>Manal</PRENOM>
            <Tele Type="fixe">0663273409</Tele>
            <Email Type="personnel">AITAYAD.manal@gmail.com</Email>
            <DateDenaissance>2001-12-30</DateDenaissance>
            <adresse>
                <rue>OUAD EL BACHA</rue>
                <Ville>SAFI</Ville>
                <numero>102</numero>
            </adresse>
        </etudiant>
        <etudiant IDEtu="ET02"  filiere="F01">
            <CIN>PE309145</CIN>
            <NOM>AIT TALEB</NOM>
            <PRENOM>Othmane</PRENOM>
            <Tele Type="fixe">0638209412</Tele>
            <Email Type="personnel">AITTALEB.othman@gmail.com</Email>
            <DateDenaissance>2001-09-18</DateDenaissance>
            <adresse>
                <rue>EL BIYAR</rue>
                <Ville>SAFI</Ville>
                <numero>263</numero>
            </adresse>
        </etudiant>
        <etudiant IDEtu="ET03"  filiere="F01">
            <CIN>HE209817</CIN>
            <NOM>ALIOUI</NOM>
            <PRENOM>HAMZA</PRENOM>
            <Tele Type="fixe">0723519826</Tele>
            <Email Type="personnel">ALIOUI.hamza@gmail.com</Email>
            <DateDenaissance>2001-03-29</DateDenaissance>
            <adresse>
                <rue>NWACER</rue>
                <Ville>CASA</Ville>
                <numero>873</numero>
            </adresse>
        </etudiant>
        <etudiant IDEtu="ET04" filiere="F01" >
            <CIN>HE356192</CIN>
            <NOM>ANTAR</NOM>
            <PRENOM>Jalila</PRENOM>
            <Tele Type="fixe">0625187329</Tele>
            <Email Type="personnel">ANTAR.jalila@gmail.com</Email>
            <DateDenaissance>2001-01-29</DateDenaissance>
            <adresse>
                <rue>MASIRA</rue>
                <Ville>SAFI</Ville>
                <numero>183</numero>
            </adresse>
        </etudiant>
        <etudiant IDEtu="ET05" filiere="F01" >
            <CIN>KH652781</CIN>
            <NOM>ARJOUZI</NOM>
            <PRENOM>Abderrahman</PRENOM>
            <Tele Type="fixe">0762410985</Tele>
            <Email Type="personnel">ARJOUZI.abderahman@gmail.com</Email>
            <DateDenaissance>2001-03-23</DateDenaissance>
            <adresse>
                <rue>OKBA BNOU NAFIAA</rue>
                <Ville>SAFI</Ville>
                <numero>305</numero>
            </adresse>
        </etudiant>
        <etudiant IDEtu="ET06"  filiere="F01" >
            <CIN>ZN675324</CIN>
            <NOM>AZINDA</NOM>
            <PRENOM>ABDELMOUNAIM</PRENOM>
            <Tele Type="fixe">0672390125</Tele>
            <Email Type="personnel">AZINDA.abdelmounim@gmail.com</Email>
            <DateDenaissance>2001-10-26</DateDenaissance>
            <adresse>
                <rue>IDRISSI</rue>
                <Ville>SAFI</Ville>
                <numero>23</numero>
            </adresse>
        </etudiant>
        <etudiant IDEtu="ET07"  filiere="F01">
            <CIN>YH876512</CIN>
            <NOM>BAHNINI</NOM>
            <PRENOM>MOUHSSINE</PRENOM>
            <Tele Type="fixe">0672398137</Tele>
            <Email Type="personnel">BAHNINI.mouhssine@gmail.com</Email>
            <DateDenaissance>2001-01-06</DateDenaissance>
            <adresse>
                <rue>KHAWARIZNI</rue>
                <Ville>YOUSOFIA</Ville>
                <numero>639</numero>
            </adresse>
        </etudiant>
        <etudiant IDEtu="ET08"  filiere="F01">
            <CIN>AB568312</CIN>
            <NOM>BAKHOUCHE</NOM>
            <PRENOM>OUIAM</PRENOM>
            <Tele Type="fixe">0572430981</Tele>
            <Email Type="personnel">BAKHOUCHE.wiam@gmail.com</Email>
            <DateDenaissance>2001-01-20</DateDenaissance>
            <adresse>
                <rue>Khalil jebrane</rue>
                <Ville>El jadida</Ville>
                <numero>31</numero>
            </adresse>
        </etudiant>
        <etudiant IDEtu="ET09"  filiere="F01">
            <CIN>TH769024</CIN>
            <NOM>BENZAHRA</NOM>
            <PRENOM>Fatima-ezzahra</PRENOM>
            <Tele Type="fixe">0628914376</Tele>
            <Email Type="personnel">BENZAHRA.fatimazahra@gmail.com</Email>
            <DateDenaissance>2001-12-01</DateDenaissance>
            <adresse>
                <rue>AMOUNI</rue>
                <Ville>SAFI</Ville>
                <numero>981</numero>
            </adresse>
        </etudiant>
        <etudiant IDEtu="ET10"  filiere="F01">
            <CIN>BE569034</CIN>
            <NOM>BOUHDADI</NOM>
            <PRENOM>RAJAA</PRENOM>
            <Tele Type="fixe">0724510876</Tele>
            <Email Type="personnel">BOUHDADI.rajaa@gmail.com</Email>
            <DateDenaissance>2001-11-09</DateDenaissance>
            <adresse>
                <rue>KINIDI</rue>
                <Ville>SAFI</Ville>
                <numero>261</numero>
            </adresse>
        </etudiant>
        <etudiant IDEtu="ET11" filiere="F01" >
            <CIN>FT453287</CIN>
            <NOM>BOUZIANE</NOM>
            <PRENOM>Amina</PRENOM>
            <Tele Type="fixe">0627912053</Tele>
            <Email Type="personnel">BOUZIANE.amina@gmail.com</Email>
            <DateDenaissance>2001-04-28</DateDenaissance>
            <adresse>
                <rue>LAMIA</rue>
                <Ville>SAFI</Ville>
                <numero>287</numero>
            </adresse>
        </etudiant>
        <etudiant IDEtu="ET12"  filiere="F01">
            <CIN>RA763267</CIN>
            <NOM>CHAHID</NOM>
            <PRENOM>YOUSSEF</PRENOM>
            <Tele Type="fixe">0714529653</Tele>
            <Email Type="personnel">CHAHID.youssef@gmail.com</Email>
            <DateDenaissance>2000-10-15</DateDenaissance>
            <adresse>
